// Mocks generated by Mockito from annotations
// in archi_draft/test/src/features/projects/providers/assignment_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:archi_draft/src/features/projects/data/assignment_repository.dart'
    as _i2;
import 'package:archi_draft/src/features/projects/domain/assignment.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AssignmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssignmentRepository extends _i1.Mock
    implements _i2.AssignmentRepository {
  MockAssignmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Assignment>> getAssignments() => (super.noSuchMethod(
    Invocation.method(#getAssignments, []),
    returnValue: _i3.Future<List<_i4.Assignment>>.value(<_i4.Assignment>[]),
  ) as _i3.Future<List<_i4.Assignment>>);

  @override
  _i3.Future<void> acceptAssignment({
    required String? assignmentId,
    required String? projectId,
    required String? actionId,
  }) => (super.noSuchMethod(
    Invocation.method(#acceptAssignment, [], {
      #assignmentId: assignmentId,
      #projectId: projectId,
      #actionId: actionId,
    }),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> rejectAssignment({
    required String? assignmentId,
    required String? projectId,
    required String? actionId,
  }) => (super.noSuchMethod(
    Invocation.method(#rejectAssignment, [], {
      #assignmentId: assignmentId,
      #projectId: projectId,
      #actionId: actionId,
    }),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);
}
