// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8K2P3WzbJjqZjU7JCHZO4gWpi_v9PkME',
    appId: '1:471564030203:web:bb8fc985704d4d22e4e05e',
    messagingSenderId: '471564030203',
    projectId: 'archi-draft',
    authDomain: 'archi-draft.firebaseapp.com',
    storageBucket: 'archi-draft.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBIycpPuTIbTG7kubbbuwZW2ZHMopM1k',
    appId: '1:471564030203:android:80a988e5a6c0be41e4e05e',
    messagingSenderId: '471564030203',
    projectId: 'archi-draft',
    storageBucket: 'archi-draft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9OrNgvKdPf11hxKlgcLIf8goJmEJgWk',
    appId: '1:471564030203:ios:2708826a93c2445fe4e05e',
    messagingSenderId: '471564030203',
    projectId: 'archi-draft',
    storageBucket: 'archi-draft.firebasestorage.app',
    iosBundleId: 'com.draughtsmanstudio.archiDraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg9OrNgvKdPf11hxKlgcLIf8goJmEJgWk',
    appId: '1:471564030203:ios:2708826a93c2445fe4e05e',
    messagingSenderId: '471564030203',
    projectId: 'archi-draft',
    storageBucket: 'archi-draft.firebasestorage.app',
    iosBundleId: 'com.draughtsmanstudio.archiDraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8K2P3WzbJjqZjU7JCHZO4gWpi_v9PkME',
    appId: '1:471564030203:web:f5c56658940f4903e4e05e',
    messagingSenderId: '471564030203',
    projectId: 'archi-draft',
    authDomain: 'archi-draft.firebaseapp.com',
    storageBucket: 'archi-draft.firebasestorage.app',
  );
}
